### ISSUE TITLE
ValueError: CorrMM received weight with wrong type.

### ISSUE THREAD

**Issue by ArghyaPal** [mikesj-public/convolutional_autoencoder#15]
I have got this error

(50000, 28, 28) (50000, 1, 28, 28)

2

Traceback (most recent call last):
File "conv_autoencoder2.py", line 195, in
X_encoded = encode_input(encode_layer, X)
File "conv_autoencoder2.py", line 193, in encode_input
return get_output(encode_layer, inputs=X).eval()
File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 523, in eval
rval = self.fn_cacheinputs
File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in __call_
storage_map=getattr(self.fn, 'storage_map', None))
File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
reraise(exc_type, exc_value, exc_trace)
File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in call
outputs = self.fn()
ValueError: CorrMM received weight with wrong type.
Apply node that caused the error: CorrMM{(0, 0), (1, 1)}(TensorConstant{[[[[ 0. 0..0. 0.]]]]}, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 8
Inputs types: [TensorType(float32, (False, True, False, False)), TensorType(float64, 4D)]
Inputs shapes: [(50000, 1, 28, 28), (16, 1, 3, 3)]
Inputs strides: [(3136, 3136, 112, 4), (72, 72, -24, -8)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{(i0 \* (Abs((i1 + i2)) + i1 + i2))}}(TensorConstant{(1, 1, 1, 1) of 0.5}, CorrMM{(0, 0), (1, 1)}.0, InplaceDimShuffle{x,0,x,x}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
"""

**Comment by kungfujam** [comment]
I get this too

**Comment by JamesOwers** [comment]
Ok...this appears to be solved by coercing the data to be 64 bit float...I have no idea why this issue isn't encountered by more people...

change 

```
## we find the encode layer from our ae, and use it to define an encoding function

def get_layer_by_name(net, name):
    for i, layer in enumerate(net.get_all_layers()):
        if layer.name == name:
            return layer, i
    return None, None
encode_layer, encode_layer_index = get_layer_by_name(ae, 'encode')

def encode_input(encode_layer, X):
    return get_output(encode_layer, inputs=X).eval()

X_encoded = encode_input(encode_layer, X)
```

to:

```
## we find the encode layer from our ae, and use it to define an encoding function

def get_layer_by_name(net, name):
    for i, layer in enumerate(net.get_all_layers()):
        if layer.name == name:
            return layer, i
    return None, None
encode_layer, encode_layer_index = get_layer_by_name(ae, 'encode')

def encode_input(encode_layer, X):
    return get_output(encode_layer, inputs=X).eval()

X_encoded = encode_input(encode_layer, X.astype('float64'))
```

**Comment by ArghyaPal** [comment]
@kungfujam First of all, Thank You for your Help regarding this error. But, I am not very clear where exactly we have defined 'get_output', is that an built-in function?
I have got the below mentioned when I have tried with MNIST dataset. I have used the latest 
'requirements.txt'. 

I have tried with epoch = 2.

OUTPUT:  

# Neural Network with 537257 learnable parameters

## Layer information

  #  name          size

---

  0  input         1x28x28
  1  conv          32x22x22
  2  pool          32x11x11
  3  flatten       3872
  4  encode_layer  40
  5  hidden        9248
  6  unflatten     32x17x17
  7  unpool        32x34x34
  8  deconv        1x28x28
  9  output_layer  784

  epoch    train loss    valid loss    train/val  dur

---

```
  1       0.42456       0.20819      2.03932  482.47s
      2       0.17246       0.14596      1.18157  494.15s
```

/home/ravishankaradepu/.local/lib/python2.7/site-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.py:764: UserWarning: The 'save_weights_to' method will be removed in nolearn 0.6. Please use 'save_params_to' instead.
  warn("The 'save_weights_to' method will be removed in nolearn 0.6. "
(50000, 28, 28) (50000, 1, 28, 28)
4594
Traceback (most recent call last):
  File "mnist_conv_autoencode.py", line 234, in <module>
    X_encoded = encode_input(encode_layer, X.astype('float64'))
  File "mnist_conv_autoencode.py", line 232, in encode_input
    return get_output(encode_layer, inputs=X).eval()
NameError: global name 'get_output' is not defined
"

Regards.

**Comment by JamesOwers** [comment]
get_output is defined at the top of the file. ctrl+f the file and you'll
see the cell that contains it.

**Comment by ArghyaPal** [comment]
@kungfujam  Oh I see.
If I am not wrong I can see **get_output**  at 
: _"mnist_conv_autoencode.ipynb"_

But, I am using _"mnist_conv_autoencode.py"_
So, any possible update for that? 

Thank You in advance for Your Help Sir,
Regards.

**Comment by ArghyaPal** [comment]
@kungfujam Ohh I see...
If I am not wrong, this **get_output** is defined at;
**_mnist_conv_autoencode.ipynb_** 

But, just curious to know, what will be the modification for _**mnist_conv_autoencode.py**_ ? 

Thank You in Advance Sir,
With Best Regards.

**Comment by JamesOwers** [comment]
My proposed fix is for the .ipynb. You can see that the .ipynb imports get output directly wheras the .py just imports the lasagne layers class. To fix this either revert your change and follow the error back or import get_output at the top i.e. add

`from lasagne.layers import get_output`

For your reference:
get_output is called on line https://github.com/mikesj-public/convolutional_autoencoder/blob/master/mnist_conv_autoencode.py#L219

It's from lasagne layers, imported line https://github.com/mikesj-public/convolutional_autoencoder/blob/master/mnist_conv_autoencode.py#L7

The line which causes the error you can work back from line https://github.com/mikesj-public/convolutional_autoencoder/blob/master/mnist_conv_autoencode.py#L227. It's just that, when running on a CPU, you appear to need to change the imported mnist data `X` to 64 bit. (This was not an issue when I was running on GPU). I do this in my solution by calling `.astype('float64')` on `X`. You could perhaps do this in the `.py` file by changing line line https://github.com/mikesj-public/convolutional_autoencoder/blob/master/mnist_conv_autoencode.py#L216 to `X_batches = np.split(X.astype('float64'), indices)`

Have a crack and see how you go.

**Comment by ArghyaPal** [comment]
@kungfujam I am still fighting with it. It looks good when I am using .ipynb;

But, Just for curiosity (or it may help to some other guy in future) I am trying **mnist_conv_autoencode.py**;

Possible changes I have made are as follows:
1. I have added  **from lasagne.layers import get_output**
2. I have added 
   
   *\* ## we find the encode layer from our ae, and use it to define an encoding function
   206 
   207 def get_layer_by_name(net, name):
   208     for i, layer in enumerate(net.get_all_layers()):
   209         if layer.name == name:
   210             return layer, i
   211     return None, None
   212 encode_layer, encode_layer_index = get_layer_by_name(ae, 'encode')
   213 
   214 def encode_input(encode_layer, X):
   215     return get_output(encode_layer, inputs=X).eval()
   216 
   217 X_encoded = encode_input(encode_layer, X) **
3. I have commented / deleted
   *\* 
   221 #encode_layer_index = map(lambda pair : pair[0], ae.layers).index('encode_layer')
   222 #encode_layer = ae.get_all_layers()[encode_layer_index]
   **
4. I have commented / deleted
   **
   237 #def encode_input(X):
   238 #    return get_output_from_nn(encode_layer, X)
   239 
   240 #X_encoded = encode_input(X_train)

Those are just after **224 def get_output_from_nn(last_layer, X):**
1. I am Using GPU, so I have not changed Line 216

**X_batches = np.split(X.astype('float64'), indices)**

With this I got the following error:
`
/home/ravishankaradepu/.local/lib/python2.7/site-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.py:764: UserWarning: The 'save_weights_to' method will be removed in nolearn 0.6. Please use 'save_params_to' instead.
  warn("The 'save_weights_to' method will be removed in nolearn 0.6. "
(50000, 28, 28) (50000, 1, 28, 28)
3528
Traceback (most recent call last):
  File "mnist_conv_autoencode.py", line 217, in <module>
    X_encoded = encode_input(encode_layer, X)
  File "mnist_conv_autoencode.py", line 215, in encode_input
    return get_output(encode_layer, inputs=X).eval()
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/helper.py", line 217, in get_output
    return all_outputs[layer_or_layers]
KeyError: None
`

Thanking You Sir for Your Help,
With Best Regards

**Comment by ArghyaPal** [comment]
For a Full Picture:

_
203 # <codecell>
204 
205 ## we find the encode layer from our ae, and use it to define an encoding function
206 
207 def get_layer_by_name(net, name):
208     for i, layer in enumerate(net.get_all_layers()):
209         if layer.name == name:
210             return layer, i
211     return None, None
212 encode_layer, encode_layer_index = get_layer_by_name(ae, 'encode')
213 
214 def encode_input(encode_layer, X):
215     return get_output(encode_layer, inputs=X).eval()
216 
217 X_encoded = encode_input(encode_layer, X)
218 
219 
220 

221 #encode_layer_index = map(lambda pair : pair[0], ae.layers).index('encode_layer')
222 #encode_layer = ae.get_all_layers()[encode_layer_index]

223 
224 def get_output_from_nn(last_layer, X):
225     indices = np.arange(128, X.shape[0], 128)
226     sys.stdout.flush()
227 
228     # not splitting into batches can cause a memory error
229     X_batches = np.split(X.astype('float64'), indices)
230     out = []
231     for count, X_batch in enumerate(X_batches):
232         out.append(layers.helper.get_output(last_layer, X_batch).eval())
233         sys.stdout.flush()
234     return np.vstack(out)
235 
236 

237 #def encode_input(X):
238 #    return get_output_from_nn(encode_layer, X)
239 
240 #X_encoded = encode_input(X_train)
241 

242 # <codecell>

_

**Comment by ArghyaPal** [comment]
For a Full Picture:

_
203 # <codecell>
204 
205 ## we find the encode layer from our ae, and use it to define an encoding function
206 
207 def get_layer_by_name(net, name):
208     for i, layer in enumerate(net.get_all_layers()):
209         if layer.name == name:
210             return layer, i
211     return None, None
212 encode_layer, encode_layer_index = get_layer_by_name(ae, 'encode')
213 
214 def encode_input(encode_layer, X):
215     return get_output(encode_layer, inputs=X).eval()
216 
217 X_encoded = encode_input(encode_layer, X)
218 
219 
220 

221 #encode_layer_index = map(lambda pair : pair[0], ae.layers).index('encode_layer')
222 #encode_layer = ae.get_all_layers()[encode_layer_index]

223 
224 def get_output_from_nn(last_layer, X):
225     indices = np.arange(128, X.shape[0], 128)
226     sys.stdout.flush()
227 
228     # not splitting into batches can cause a memory error
229     X_batches = np.split(X.astype('float64'), indices)
230     out = []
231     for count, X_batch in enumerate(X_batches):
232         out.append(layers.helper.get_output(last_layer, X_batch).eval())
233         sys.stdout.flush()
234     return np.vstack(out)
235 
236 

237 #def encode_input(X):
238 #    return get_output_from_nn(encode_layer, X)
239 
240 #X_encoded = encode_input(X_train)
241 

242 # <codecell>

_

**Comment by ArghyaPal** [comment]
Finally I figure it out:

Change the following;

`def get_output_from_nn(last_layer, X): #.astype(np.float32)):
    print "Here 5\n";
    indices = np.arange(128, X.shape[0], 128)
    sys.stdout.flush()

```
# not splitting into batches can cause a memory error
X_batches = np.split(X, indices)
out = []
print "Here 6\n";
for count, X_batch in enumerate(X_batches):
    out.append(last_layer.get_output(X_batch).eval())
    sys.stdout.flush()
return np.vstack(out)`
```

to;

`def get_output_from_nn(last_layer, X): #.astype(np.float32)):
    print "Here 5\n";
    indices = np.arange(128, X.shape[0], 128)
    sys.stdout.flush()

```
# not splitting into batches can cause a memory error
X_batches = np.split(X, indices)
out = []
print "Here 6\n";
for count, X_batch in enumerate(X_batches):
    *out.append(last_layer.get_output(X_batch.astype(np.float64)).eval())*
    sys.stdout.flush()
return np.vstack(out)`
```
